version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thanhle0405
      POSTGRES_DB: shopping_store
    ports:
      - "5432:5432"

  backend:
    build: backend/.
    ports: 
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: frontend/.
    ports: 
      - "80:80"
    depends_on: 
      - backend