name: CI Pipeline (Build & Test)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  backend-test:
    name: Backend Test (Java)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    
    steps:
      - uses: actions/checkout@v4

      - name: Cài đặt Java JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Chạy Unit Test Backend
        run: mvn clean test -DskipTests=true # Bỏ qua ngắt kết nối DB nếu chưa cấu hình DB Test

  frontend-test:
    name: Frontend Build (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Cài đặt Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Cài đặt các thư viện Frontend
        run: npm install

      - name: Kiểm tra Build Code
        run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider